### ISSUE TITLE
Can work with Broadcom wifi module?

### ISSUE THREAD

**Issue by liqili** [ljzxzxl/gigabyte-h470i-hackintosh-efi#1]
Is this board wifi CNVI locked?

**Comment by ljzxzxl** [comment]
Yes, The onboard wireless network card cannot be replaced with a Broadcom wireless network card Because of CNVI.

**Comment by ljzxzxl** [comment]
Yes, The onboard wireless network card cannot be replaced with a Broadcom wireless network card Because of CNVI.
